key_words = {
    'Advocate': {
        'legal': 5,
        'court': 4,
        'litigation': 4,
        'legal counsel': 5,
        'lawyer': 5,
        'advocacy': 4,
        'legal advisor': 4,
        'legal aid': 4,
        'judicial': 3,
        'counselor': 3,
        'attorney': 5,
        'legal services': 4,
        'case management': 4,
        'client representation': 4,
        'legal consultation': 4,
        'defendant': 3,
        'plaintiff': 3,
        'paralegal': 4,
        'legal research': 4,
        'courtroom': 4
    },
    'Arts': {
        'creative': 4,
        'visual arts': 4,
        'fine arts': 4,
        'performing arts': 4,
        'artistic expression': 4,
        'painting': 4,
        'sculpture': 4,
        'music': 4,
        'theatre': 4,
        'creative writing': 4,
        'art history': 3,
        'exhibition': 3,
        'art gallery': 3,
        'craftsmanship': 4,
        'design': 4,
        'artistic vision': 4,
        'artistic mediums': 3,
        'artistic techniques': 3,
        'artistic creativity': 4
    },
    'Automation Testing': {
        'automated testing': 4,
        'test automation': 4,
        'selenium': 4,
        'test scripts': 4,
        'qa automation': 4,
        'test framework': 4,
        'quality assurance': 4,
        'regression testing': 4,
        'test cases': 4,
        'test suites': 3,
        'software testing': 4,
        'continuous integration': 3,
        'test automation tools': 4,
        'functional testing': 4,
        'load testing': 4,
        'scripting': 3,
        'test execution': 4,
        'quality control': 3,
        'test plans': 4,
        'performance testing': 4
    },
    'Blockchain': {
        'cryptocurrency': 4,
        'distributed ledger': 4,
        'smart contracts': 4,
        'blockchain technology': 4,
        'bitcoin': 4,
        'ethereum': 4,
        'decentralized': 4,
        'consensus algorithm': 4,
        'cryptographic hash': 4,
        'transaction validation': 4,
        'blockchain network': 4,
        'digital tokens': 4,
        'blockchain development': 4,
        'hyperledger': 4,
        'public key': 4,
        'private key': 4,
        'cryptographic security': 4,
        'mining': 4,
        'blockchain consensus': 4,
        'blockchain explorer': 4
    },
    'Business Analyst': {
        'business analysis': 5,
        'requirements gathering': 5,
        'business process': 4,
        'data analysis': 4,
        'business requirements': 4,
        'stakeholder management': 4,
        'use case': 4,
        'process improvement': 4,
        'requirement elicitation': 4,
        'functional specification': 4,
        'gap analysis': 4,
        'swot analysis': 4,
        'requirement validation': 4,
        'business metrics': 4,
        'user stories': 4,
        'data modeling': 4,
        'business intelligence': 4,
        'decision support': 4,
        'financial analysis': 4,
        'market research': 4
    },
    'Civil Engineer': {
        'structural engineering': 4,
        'construction': 4,
        'civil engineering': 4,
        'infrastructure': 4,
        'civil design': 4,
        'geotechnical engineering': 4,
        'land development': 4,
        'surveying': 4,
        'construction management': 4,
        'bridge design': 4,
        'environmental engineering': 4,
        'materials testing': 4,
        'project management': 4,
        'autocad': 4,
        'hydraulics': 4,
        'site development': 4,
        'transportation engineering': 4,
        'water resources': 4,
        'concrete': 4,
        'steel structures': 4
    },
    'Data Science': {
        'data analysis': 5,
        'machine learning': 5,
        'data modeling': 4,
        'data mining': 4,
        'predictive analytics': 4,
        'big data': 4,
        'statistical analysis': 4,
        'data visualization': 4,
        'artificial intelligence': 5,
        'python': 5,
        'r programming': 4,
        'deep learning': 4,
        'natural language processing': 4,
        'data warehousing': 4,
        'feature engineering': 4,
        'hadoop': 4,
        'spark': 4,
        'data cleaning': 4,
        'data scientist': 5,
        'analytics': 4
    },
    'Database': {
        'database management': 4,
        'sql': 4,
        'database administration': 4,
        'data retrieval': 4,
        'database design': 4,
        'relational database': 4,
        'nosql': 4,
        'data warehouse': 4,
        'data integrity': 4,
        'query optimization': 4,
        'database security': 4,
        'stored procedures': 4,
        'data backup': 4,
        'data migration': 4,
        'etl process': 4,
        'database schema': 4,
        'normalization': 4,
        'database performance': 4,
        'indexing': 4,
        'backup and recovery': 4
    },
    'DevOps Engineer': {
        'continuous integration': 4,
        'continuous deployment': 4,
        'ci/cd pipeline': 4,
        'automation': 4,
        'docker': 4,
        'kubernetes': 4,
        'version control': 4,
        'infrastructure as code': 4,
        'containerization': 4,
        'devops tools': 4,
        'scripting': 4,
        'deployment automation': 4,
        'monitoring': 4,
        'cloud computing': 4,
        'release management': 4,
        'scalability': 4,
        'server configuration': 4,
        'orchestration': 4,
        'system administration': 4,
        'devops culture': 4
    },
    'DotNet Developer': {
        'c#': 4,
        '.net framework': 4,
        '.net core': 4,
        'asp.net': 4,
        'web development': 4,
        'visual studio': 4,
        'mvc': 4,
        'entity framework': 4,
        'web api': 4,
        'wpf': 4,
        'winforms': 4,
        'linq': 4,
        'database connectivity': 4,
        'oop': 4,
        'software development': 4,
        'unit testing': 4,
        'code debugging': 4,
        'software design': 4,
        'version control': 4
    },
    'ETL Developer': {
        'extract, transform, load': 4,
        'data integration': 4,
        'etl process': 4,
        'data extraction': 4,
        'data transformation': 4,
        'data loading': 4,
        'etl tools': 4,
        'data warehouse': 4,
        'data mapping': 4,
        'data cleansing': 4,
        'sql': 4,
        'etl jobs': 4,
        'data migration': 4,
        'etl testing': 4,
        'data quality': 4,
        'etl architecture': 4,
        'data integration patterns': 4,
        'etl framework': 4,
        'data flow': 4
    },
    'Electrical Engineering': {
        'electronic circuits': 4,
        'electromagnetic fields': 4,
        'electric power': 4,
        'control systems': 4,
        'digital signal processing': 4,
        'microcontrollers': 4,
        'electrical design': 4,
        'power electronics': 4,
        'circuit analysis': 4,
        'embedded systems': 4,
        'analog electronics': 4,
        'pcb design': 4,
        'renewable energy': 4,
        'robotics': 4,
        'sensors': 4,
        'electrical safety': 4,
        'rf engineering': 4,
        'semiconductor devices': 4,
        'instrumentation': 4
    },
    'HR': {
        'human resources': 4,
        'recruitment': 4,
        'talent management': 4,
        'employee relations': 4,
        'hr policies': 4,
        'performance appraisal': 4,
        'workforce planning': 4,
        'employee benefits': 4,
        'compensation': 4,
        'labor laws': 4,
        'organizational development': 4,
        'hr metrics': 4,
        'training and development': 4,
        'hris': 4,
        'employee engagement': 4,
        'onboarding': 4,
        'conflict resolution': 4,
        'diversity and inclusion': 4,
        'hr compliance': 4
    },
    'Hadoop': {
        'hadoop': 4,
        'big data': 4,
        'hadoop ecosystem': 4,
        'hive': 4,
        'hdfs': 4,
        'mapreduce': 4,
        'hbase': 4,
        'pig': 4,
        'spark': 4,
        'yarn': 4,
        'nosql': 4,
        'data processing': 4,
        'distributed computing': 4,
        'data warehousing': 4,
        'data analytics': 4,
        'cloudera': 4,
        'hortonworks': 4,
        'hadoop administration': 4,
        'hadoop streaming': 4,
        'hadoop development': 4
    },
    'Health and fitness': {
        'fitness': 4,
        'wellness': 4,
        'nutrition': 4,
        'exercise': 4,
        'healthcare': 4,
        'physical activity': 4,
        'healthy lifestyle': 4,
        'dietary guidelines': 4,
        'sports medicine': 4,
        'fitness training': 4,
        'wellness programs': 4,
        'personal trainer': 4,
        'health promotion': 4,
        'weight management': 4,
        'cardiovascular health': 4,
        'strength training': 4,
        'yoga': 4,
        'mental health': 4,
        'public health': 4,
        'holistic health': 4
    },
    'Java Developer': {
        'java': 4,
        'j2ee': 4,
        'spring framework': 4,
        'java servlets': 4,
        'jsp': 4,
        'hibernate': 4,
        'restful web services': 4,
        'maven': 4,
        'spring boot': 4,
        'web development': 4,
        'java swing': 4,
        'javafx': 4,
        'soap web services': 4,
        'object-oriented programming': 4,
        'design patterns': 4,
        'java development kit': 4,
        'application development': 4,
        'unit testing': 4,
        'code optimization': 4,
        'java libraries': 4
    },
    'Mechanical Engineer': {
        'mechanical engineering': 4,
        'solidworks': 4,
        'autocad': 4,
        'thermodynamics': 4,
        'fluid mechanics': 4,
        'mechanical design': 4,
        'manufacturing processes': 4,
        'materials science': 4,
        'machine design': 4,
        'product development': 4,
        'mechatronics': 4,
        'finite element analysis': 4,
        'cad/cam': 4,
        'heat transfer': 4,
        'robotics': 4,
        'aerospace engineering': 4,
        'hvac': 4,
        'maintenance engineering': 4,
        'engineering drawings': 4
    },
    'Network Security Engineer': {
        'network security': 4,
        'firewalls': 4,
        'intrusion detection': 4,
        'vulnerability assessment': 4,
        'cybersecurity': 4,
        'security protocols': 4,
        'siem': 4,
        'network monitoring': 4,
        'access control': 4,
        'security policies': 4,
        'threat analysis': 4,
        'penetration testing': 4,
        'data encryption': 4,
        'network defense': 4,
        'incident response': 4,
        'security auditing': 4,
        'firewall configuration': 4,
        'ids/ips': 4,
        'security certifications': 4,
        'network architecture': 4
    },
    'Operations Manager': {
        'operations management': 4,
        'process improvement': 4,
        'supply chain management': 4,
        'logistics': 4,
        'quality control': 4,
        'project management': 4,
        'business process': 4,
        'inventory management': 4,
        'strategic planning': 4,
        'leadership': 4,
        'team management': 4,
        'budget management': 4,
        'operational efficiency': 4,
        'resource allocation': 4,
        'vendor management': 4,
        'risk management': 4,
        'performance metrics': 4,
        'continuous improvement': 4,
        'change management': 4,
        'operational excellence': 4
    },
    'PMO': {
        'project management office': 4,
        'project management': 4,
        'pmo processes': 4,
        'project portfolio management': 4,
        'pmo governance': 4,
        'project delivery': 4,
        'project planning': 4,
        'risk management': 4,
        'resource management': 4,
        'quality management': 4,
        'pmo tools': 4,
        'project lifecycle': 4,
        'agile project management': 4,
        'stakeholder management': 4,
        'pmo metrics': 4,
        'project reporting': 4,
        'program management': 4,
        'pmo standards': 4,
        'pmo strategy': 4,
        'pmo leadership': 4
    },
    'Python Developer': {
        'python': 4,
        'django': 4,
        'flask': 4,
        'web development': 4,
        'python libraries': 4,
        'restful apis': 4,
        'data science': 4,
        'machine learning': 4,
        'python scripting': 4,
        'debugging': 4,
        'unit testing': 4,
        'object-oriented programming': 4,
        'data analysis': 4,
        'python frameworks': 4,
        'automation': 4,
        'web scraping': 4,
        'data visualization': 4,
        'database integration': 4,
        'code optimization': 4,
        'software development': 4
    },
    'SAP Developer': {
        'sap': 4,
        'sap modules': 4,
        'abap': 4,
        'sap hana': 4,
        'sap erp': 4,
        'sap implementation': 4,
        'sap configuration': 4,
        'sap customization': 4,
        'sap integration': 4,
        'sap fiori': 4,
        'sap security': 4,
        'sap netweaver': 4,
        'sap business warehouse': 4,
        'sap analytics': 4,
        'sap s/4hana': 4,
        'sap ui5': 4,
        'sap data migration': 4,
        'sap support': 4,
        'sap testing': 4,
        'sap business intelligence': 4
    },
    'Sales': {
        'sales': 4,
        'sales strategy': 4,
        'customer relationship': 4,
        'sales pipeline': 4,
        'sales targets': 4,
        'negotiation': 4,
        'sales techniques': 4,
        'sales cycle': 4,
        'lead generation': 4,
        'sales team management': 4,
        'customer acquisition': 4,
        'b2b sales': 4,
        'b2c sales': 4,
        'sales forecasting': 4,
        'key account management': 4,
        'sales presentations': 4,
        'closing sales': 4,
        'sales metrics': 4,
        'sales process': 4,
        'cold calling': 4
    },
    'Testing': {
        'software testing': 4,
        'manual testing': 4,
        'automated testing': 4,
        'test cases': 4,
        'test scripts': 4,
        'regression testing': 4,
        'quality assurance': 4,
        'test planning': 4,
        'test execution': 4,
        'defect tracking': 4,
        'test management': 4,
        'test automation': 4,
        'load testing': 4,
        'performance testing': 4,
        'testing tools': 4,
        'user acceptance testing': 4,
        'integration testing': 4,
        'test reporting': 4,
        'qa processes': 4,
        'agile testing': 4
    },
    'Web Designing': {
        'web design': 10,
        'front-end development': 10,
        'web ui': 10,
        'html': 10,
        'css': 10,
        'javascript': 10,
        'js': 10,
        'wordpress': 10,
        'design': 10,
        'ui': 10,
        'photoshop': 10,
        'jquery': 10,
        'ux': 10,
        'html5': 10,
        'sketch': 10,
        'projects': 10,
        'web designer': 10,
        'drupal': 10,
        'joomla': 10,
        'react': 10,
        'ui/ux': 10,
        'user interface design': 10,
        'responsive design': 10,
        'web graphics': 10,
        'ui/ux design': 10,
        'web development': 10,
        'wireframing': 10,
        'web prototyping': 10,
        'web accessibility': 10,
        'cross-browser compatibility': 10,
        'mobile-first design': 10,
        'web animation': 10,
        'user-centered design': 10,
        'web design software': 10,
        'web design trends': 10
    }
}


def get_key_words():
    return key_words
